# docker-compose -p project_name up -d
name: webook
services:
    mysql:
        image: mysql:8.4.5
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./script/init_webook.sql:/docker-entrypoint-initdb.d/
        ports:
          - 3306:3306
    redis:
        image: redis:7.4-alpine
        restart: always
        environment:
            - REDIS_PASSWORD=root
        ports:
          - 6379:6379
    # # kafka:
    # mongodb:
    # etcd
    # minio:
    # 可观测性
    # elasticsearch:
    # logstash:
    # kibana
    # prometheus:
    # zipkin:
    # grafana:
    # 
    # canal: