version: '3'
services:
    etcd:
      image: 'bitnami/etcd:3.4.32'
      container_name: etcd
      restart: 'no'  
      environment:
        - ALLOW_NONE_AUTHENTICATION=yes
      ports:
        - 2379:2379
      networks:
        - my-network
networks:
  my-network: 
    external: true
    name: egoist