version: '3'
services:
  kafka:
   image: 'bitnami/kafka:3.3.1'
   container_name: "kafka"
   restart: 'no'  
   networks:
      - my-network
   ports:
     - 9192:9092
     - 9193:9093
   environment:
     ### 通用配置
     # 允许使用kraft，即Kafka替代Zookeeper
     - KAFKA_ENABLE_KRAFT=yes
networks:
  my-network: 
    external: true
    name: egoist