version: '3'
services:
  mongo:
    image: mongo:7.0.10-rc0
    container_name: mongodb
    restart: 'no'  
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data/db:/data/db
      - ./mongo/data/configdb:/data/configdb
      - ./mongo/data/logs:/data/logs
      #启动参数 --auth 连接需要用户名和密码
#    command: --auth
    networks:
      - my-network
networks:
  my-network: 
    external: true
    name: egoist