version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql8.0
    restart: 'no'  
    command: 
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/log:/var/log/mysql
    networks:
      - my-network
networks:
  my-network: 
    external: true
    name: egoist