version: '3'
services:
  portainer:
#    portainer来查看可视化容器页面：
    image: portainer/portainer
    container_name: portainer
    ports:
      - 9000:9000
    restart: no
    volumes:
      - ./portainer/localtime:/etc/localtime
      - ./portainer/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data:rw
    networks:
      - my-network
networks:
  my-network: 
    external: true
    name: egoist