version: '3'
services:
  redis:
    image: redis:7.2.4
    container_name: redis
    restart: 'no'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - http.host=0.0.0.0
    ports:
      - 6379:6379
    networks:
      - my-network
    volumes:
      - ./redis/data:/data:rw
networks:
  my-network: 
    external: true
    name: egoist